Title: Git Complete Guide
Description: A Comprehensive Guide to Git for Version Control and Collaboration. This guide covers everything from Git basics to advanced workflows, including branching strategies, rebasing, merging, undoing changes, troubleshooting, and best practices for efficient version control.

remote_theme: "pages-themes/slate@v0.2.0"
plugins:
  - jekyll-remote-theme